"""rebuild after broken history

Revision ID: 36bcff0587ba
Revises: 
Create Date: 2025-07-31 23:04:54.960003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bcff0587ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('admins', 'is_active')
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'verified')
    op.add_column('admins', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'verified')
    # ### end Alembic commands ###
