"""Add is_active to admin

Revision ID: 84abdefc539f
Revises: 9cecb9bb9aa0
Create Date: 2025-07-23 17:54:09.020180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84abdefc539f'
down_revision: Union[str, None] = '9cecb9bb9aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_active')
    # ### end Alembic commands ###
