"""add first_name and last_name to users

Revision ID: 9cecb9bb9aa0
Revises: 2cdcd0acbe0f
Create Date: 2025-07-23 16:32:46.532365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cecb9bb9aa0'
down_revision: Union[str, None] = '2cdcd0acbe0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))

    # Optional: populate for existing users
    op.execute("UPDATE users SET first_name = 'John' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = 'Doe' WHERE last_name IS NULL")

    # Now make them NOT NULL
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)

    op.drop_column('users', 'name')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
